### ISSUE TITLE
Easy way to install custom plugins

### ISSUE THREAD

**Issue by ricardobeat** [nate-parrott/Flashlight#178]
There should be at least one of the following ways of adding a custom (private or modified) bundle:
1. "Import plugin" from the File menu
2. Drag & Drop a `.bundle` into the app
3. switch from `.bundle` to a custom extension that auto-installs when opened

**Comment by ricardobeat** [comment]
Hello?

**Comment by nate-parrott** [comment]
Sorry, didn't see this until now!

You can currently add your own plugins by dropping them in
~/Library/FlashlightPlugins.
It would make sense to create a new extension for Flashlight plugins,
rather than .bundle — then, you could automatically install plugins by
double-clickign them.

Alternatively — this is something I've thought about for a long time —
would it be useful to be able to ship Flashlight plugins *inside* other
apps? Like, inside the resources folder of your app, include a Flashlight
plugin, and have Flashlight automatically pick it up?

Let me know what you think.

**Comment by ricardobeat** [comment]
An extension would work nicely. What do you think about drag & drop also? It would make the process friendly for non-tech-savvy users, and is probably easier to implement.

Regarding apps, I don't have that need atm so don't really have an opinion, but it does sound like a nice feature. Install app, get spotlight extras automatically.
