### ISSUE TITLE
Github open repository directly by github plugin.

### ISSUE THREAD

**Issue by mtunique** [nate-parrott/Flashlight#269]
Github open repository directly by github plugin.
Does the github plugin decide to get the feature?
If yes, maybe I can make a PR for it.

**Comment by marcbachmann** [comment]
Since yesterday there's a github issue plugin.
Maybe we should merge everything and make one plugin which triggers
different actions based on the first argument of the query.

On 14 Jan 2015, at 04:29, Tao Meng <notifications@github.com> wrote:

Github open repository directly by github plugin.
Does the github plugin decide to get the feature?
If yes, maybe I can make a PR for it.

—
Reply to this email directly or view it on GitHub
<https://github.com/nate-parrott/Flashlight/issues/269>.

**Comment by mtunique** [comment]
thx
