### ISSUE TITLE
Install Flashlight, El Capitan, Rootless removed.

### ISSUE THREAD

**Issue by tiferrei** [nate-parrott/Flashlight#554]
Hi, as the title says, I removed rootless protection because I needed it to install some dev tools, so shouldn't my flashlight work?

**Comment by Sajonara** [comment]
No, because a core library changed as well (SIMBL). You need to install it, and tell OS X to use it instead of its own version. And if you do, some of the OS X features might stop working. You can participate on a discussion of the future of this project though, because the author won't update it, the way it works right now. Cf. https://github.com/nate-parrott/Flashlight/issues/537

**Comment by orbitly** [comment]
If you Flashlight through SIMBL manually then spotlight just crashes, incompatible with El Cap. Needs a little coding work, work that none of the hundreds of commenters in that thread know how to do, and Nate Parrot doesn't have time to do. So it's up to you and everyone else that is capable of learning to program to fix. Thousands of people will love whoever fixes it forever.

**Comment by tiferrei** [comment]
Ah ok, well I think we can close this by now, if anyone has a new idea to solve this, please reopen.
