### ISSUE TITLE
is it worth the risk to disable rootless for flashlight

### ISSUE THREAD

**Issue by rmnattas** [nate-parrott/Flashlight#555]
i just found flash light and sadly found it does not work in OS X 10.11 so i saw the plugins in flashlight, and i came around 23 plugin that ill install for sure and it will help me a lot.

but my brain is in fight if i should disable the rootless or not, does it relay help with a lot of malware or just some little of them. I WANT IT WHY YOU APPLE 😩.

**Comment by Sajonara** [comment]
Even if you disable rootless, you won't be able to run Flashlight out of the box. You still have incompatibilities with one of the core libraries and would need to install SIMBL and tell OS X to listen to SIMBL instead of its own version. But if you do maybe some OS X' functions won't work in the end. So if I were you, don't disable it. The author of the plugin won't update it, and a discussion on the future of this plugin is already on track. Cf. https://github.com/nate-parrott/Flashlight/issues/537

**Comment by rmnattas** [comment]
😩 i just disable rootless and try it didn't work and you commented in the same time, looks like ill enable rootless again 😢 IT WAS MY BEST APP EVER(even i didn't use it). 😢

**Comment by Sajonara** [comment]
@rmnattas I used it a lot and it's a pity that is does no longer work. But maybe there will be a substitute one day. Or Apple will integrate some of the features or provide an API to extend Spotlight. It already has done this on iOS. App developers can populate Spotlight search on iOS with their search results.

**Comment by rmnattas** [comment]
Right. They didt in ios so they may do it in mac and i hope fast
